version: '3.8'

services:
  # Fabric CA (Certificate Authority)
  fabric-ca:
    container_name: fabric-ca
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto:/etc/hyperledger/fabric-ca
    networks:
      - fabric_test

  # Fabric Tools (for testing and management)
  fabric-tools:
    container_name: fabric-tools
    image: hyperledger/fabric-tools:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto:/etc/hyperledger/fabric/crypto
      - ./scripts:/scripts
    working_dir: /scripts
    networks:
      - fabric_test
    depends_on:
      - fabric-ca
    command: tail -f /dev/null  # Keep container running

  # Simple test peer (minimal configuration)
  fabric-peer:
    container_name: fabric-peer
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=0.0.0.0:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_CHAINCODE_MODE=net
      - CORE_CHAINCODE_STARTUPTIMEOUT=300s
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
    ports:
      - "7051:7051"
      - "7052:7052"
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/fabric
      - ./crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
    networks:
      - fabric_test
    depends_on:
      - fabric-ca
      - fabric-tools

networks:
  fabric_test:
    driver: bridge
